description: "This webpage is a test of using Jekyll to create webspaces in Github, which can do this automagically!"
email: "test+email@gmail.com"
github: "https://github.com/swcarpentry.org"
    
collections:
  blogposts:
    output: true
